### ISSUE TITLE
Padding bug in align_rigid?

### ISSUE THREAD

**Issue by phflot** [MIDA-group/globalign#1]
Thank you for your great work, I am plannig to use it for refining alignment of our multimodal recordings after camera geometry-based pre-alignment and so far it seems to works well! 
However, when running your ```example.py``` script, the images example_flo_image.png and example_flo_image_recovered.png seem to have a shift difference of 1 pixel to the right. I dug a bit into your code and ```globalalign.py``` line 306, you are calculating the modulu with the padded input sizes. Subtracting 1 from x fixes the issue, but I have not checked whether the error is actually with the padding or happens later in the transformations, maybe somebody of you could take a look?

**Comment by joakimlindblad** [comment]
Glad it works well for you @phflot !
Good catch with the 1 pixel shift-issue; thanks for reporting. (Sorry for the slow response; for unknown reason I wasn't "subscribing" to issues for this repo.)

Your guessed reason is not the real cause though, but instead the different coordinate conventions used by `torchvision.transforms.functional.rotate` (origin at upper left corner of top left pixel) and `scipy.ndimage.map_coordinates` (origin at the center of the top left pixel). This leads to a half-a-pixel offset of the center of rotation, which together with the 90-degree rotation lead to the observed shift of one pixel.

Commit 2d9065c and release [v1.0.2](https://github.com/MIDA-group/globalign/releases/tag/v1.0.2) should fix the problem.

```
$ diff -s example_flo_image_recovered.png example_flo_image.png 
Files example_flo_image_recovered.png and example_flo_image.png are identical
```
