### ISSUE TITLE
How can I use my own images for registration?

### ISSUE THREAD

**Issue by xiaoyu30108** [MIDA-group/globalign#3]
When I try to change the **ref_image** and **flo_image** in **example.py**, I find that the results are always the same.

![image](https://github.com/user-attachments/assets/28705bf3-d40b-4b97-bddf-b0e267cc6a5a)
![image](https://github.com/user-attachments/assets/3b154733-0bdd-4134-bc54-e269c74f614f)

**Comment by xiaoyu30108** [comment]
My fault！ This example.py file manually generates a rigidly transformed image for testing, enters it into the globalign file for processing, and outputs this rigid transformation.Is that right?

**Comment by joakimlindblad** [comment]
That is correct
